name = "gridflow-solar-web"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[assets]
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"
